### PR TITLE
Problem: pgmigrate.sh failed to install migrate under Golang v1.15 or below

### LINKED ISSUE #468: Problem: pgmigrate.sh failed to install migrate under Golang v1.15 or below
According to https://github.com/golang-migrate/migrate/tree/master/cmd/migrate#versioned, `golang-migrate` has different installation options based on Golang version

### PR DESCRIPTION
**Pull request by calvinaco**
Solution: (Fix #468) Update script to install migrate based on Golang version

### CODE REVIEW

File: pgmigrate.sh [hunk 1]
```diff
@@ -58,18 +121,27 @@ while [[ $# > 0 ]]; do
...
+    if [[ "${INSTALL_DEPENDENCY}" == 0 ]]; then
+        if [[ "${RET_VALUE}" == "NOT_FOUND" ]]; then
+            echoerr "Cannot find migrate. Provide \`--install-dependency\` to try to install it."
+            exit 1
+        fi
+    else
+        is_golang_1_16_and_above
+        if [[ "${RET_VALUE}" == 1 ]]; then
+#            install_golang_migrate_golang_1_16_and_above
+            install_golang_migrate_universal
```
Comment (davcrypto) [inline pgmigrate.sh:135]: Looks like no difference between `if` and `else` clause as install_golang_migrate_universal is running `install_golang_migrate_golang_1_15_and_below`

Comment (davcrypto) [reply pgmigrate.sh:135]: I guess `install_golang_migrate_golang_1_16_and_above` should be uncommented?

Comment (calvinaco) [reply pgmigrate.sh:135]: This is intended. I tried `install_golang_migrate_golang_1_16_and_above` at the beginning but I realize the `migrate` installed using this method has `migrate --version` always returns `dev` so it confuses the version check.

However, I want to keep the code here for future reference because this is the recommended way.

File: pgmigrate.sh [hunk 2]
```diff
@@ -58,18 +121,27 @@ while [[ $# > 0 ]]; do
...
+        else
+            install_golang_migrate_golang_1_15_and_below
+        fi
```
Comment (calvinaco) [inline pgmigrate.sh:138]:
```suggestion
        install_golang_migrate_universal
```

File: pgmigrate.sh (hunk 1 above)
Comment (davcrypto) [reply pgmigrate.sh]: I see
